
version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_backend
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db-rds.c6tw468eujha.us-east-1.rds.amazonaws.com:3306/library_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123456
      AWS_BUCKET_NAME: library-system-storage-2026
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY: 
      AWS_SECRET_KEY: 